### ISSUE TITLE
Integration Luftdaten not working v0.114

### ISSUE THREAD

**Issue by waverider020** [lichtteil/local_luftdaten#17]
I cant add the luftdaten intergration. After trying many times sometimes it does add but there are no entities. 
![B4270AE3-C44A-44F7-BDFC-D20214C0F082](https://user-images.githubusercontent.com/65109592/90974133-9802e300-e528-11ea-999a-4cee4af5145c.png)

**Comment by waverider020** [comment]
I seem to work again.

**Comment by lichtteil** [comment]
@waverider020 did you use this custom component or the official Luftdaten integration https://www.home-assistant.io/integrations/luftdaten/ ?

**Comment by waverider020** [comment]
I used the luftdaten integration, it wirks afain at the moment. 


Vriendelijke groeten

Peter

**Comment by lichtteil** [comment]
If you have trouble with the official integration you have to submit the issue to the Home Assistant repository.
I found there an issue that sound just like yours: https://github.com/home-assistant/core/issues/39187

I hope you can solve it! Because I can only help with this custom integration I will close the issue for now.

**Comment by waverider020** [comment]
And it is broken again! 

Vriendelijke groeten

Peter Meijboom

**Comment by waverider020** [comment]
Thank you. It stopt working again. I will put a comment to your suggested repository. 

Vriendelijke groeten

Peter Meijboom
